/**
 * Base storage module - Shared utilities and database client
 * All storage modules import from this base module
 */

import { db } from "../db";

// Re-export the database client for use in all storage modules
export { db };

// Re-export all schema tables and types that are commonly used
export {
  // Tables
  users,
  vehicles,
  appointments,
  jobCards,
  partsInventory,
  jobCardParts,
  jobCardTasks,
  approvalRequests,
  customerNotes,
  emailCampaigns,
  coupons,
  loyaltyPointsTransactions,
  loyaltySettings,
  customerReferrals,
  jobCardTimerSessions,
  landingPageSettings,
  pricingSettings,
  invoices,
  invoiceItems,
  payments,
  invoiceNumberSequence,
  customerAccountSequence,
  estimates,
  estimateItems,
  estimateNumberSequence,
  inspections,
  inspectionItems,
  staffReviews,
  notificationPreferences,
  notificationHistory,
  badgeCounts,
  emailVerificationTokens,
  passwordResetTokens,
  emailSettings,
  rentalVehicles,
  rentalExtras,
  rentalReservations,
  rentalReservationExtras,
  rentalContracts,
  rentalPayments,
  rentalMaintenanceLog,
  rentalAvailabilityBlocks,
  rentalReservationSequence,
  rentalContractSequence,
  towTrucks,
  wreckerDrivers,
  thirdPartyWreckers,
  towRequests,
  towPricingZones,
  towRequestLocations,
  towRequestSequence,
  chatConversations,
  chatMessages,
  chatAssignments,
  chatQuickResponses,
  chatAgentStatus,
  chatRoutingSettings,
  chatSettings,
  chatRatings,
  serviceReminders,
  maintenanceSchedules,
  serviceReminderHistory,
  appointmentSettings,
  paymentGatewaySettings,
  quickbooksSettings,
  vendorNumberSequence,
  vendorBillNumberSequence,
  vendorPaymentNumberSequence,
  vendors,
  vendorBills,
  vendorBillLineItems,
  vendorPayments,
  expenses,
  expenseNumberSequence,
  paymentReminderSettings,
  paymentRemindersLog,
  leads,
  leadActivities,
  customerTags,
  customerTagAssignments,
  customerSegments,
  permissions,
  roles,
  rolePermissions,
  userPermissionOverrides,
  permissionAuditLog,
  promotionalBanners,
  vehicleDocuments,

  // Types
  type User,
  type InsertUser,
  type UpsertUser,
  type Vehicle,
  type InsertVehicle,
  type Appointment,
  type InsertAppointment,
  type JobCard,
  type InsertJobCard,
  type JobCardTask,
  type InsertJobCardTask,
  type Part,
  type InsertPart,
  type JobCardPart,
  type InsertJobCardPart,
  type ApprovalRequest,
  type InsertApprovalRequest,
  type CustomerNote,
  type InsertCustomerNote,
  type EmailCampaign,
  type InsertEmailCampaign,
  type Coupon,
  type InsertCoupon,
  type LoyaltyPointsTransaction,
  type InsertLoyaltyPointsTransaction,
  type LoyaltySettings,
  type InsertLoyaltySettings,
  type CustomerReferral,
  type InsertCustomerReferral,
  type JobCardTimerSession,
  type InsertJobCardTimerSession,
  type LandingPageSettings,
  type InsertLandingPageSettings,
  type PricingSettings,
  type InsertPricingSettings,
  type Invoice,
  type InsertInvoice,
  type InvoiceItem,
  type InsertInvoiceItem,
  type Payment,
  type InsertPayment,
  type Estimate,
  type InsertEstimate,
  type EstimateItem,
  type InsertEstimateItem,
  type Inspection,
  type InsertInspection,
  type InspectionItem,
  type InsertInspectionItem,
  type StaffReview,
  type InsertStaffReview,
  type EmailVerificationToken,
  type InsertEmailVerificationToken,
  type PasswordResetToken,
  type InsertPasswordResetToken,
  type EmailSettings,
  type InsertEmailSettings,
  type ChatConversation,
  type InsertChatConversation,
  type ChatMessage,
  type InsertChatMessage,
  type ChatAssignment,
  type InsertChatAssignment,
  type ChatQuickResponse,
  type InsertChatQuickResponse,
  type ChatAgentStatus,
  type InsertChatAgentStatus,
  type ChatRoutingSettings,
  type InsertChatRoutingSettings,
  type ChatRating,
  type InsertChatRating,
  type ChatSettings,
  type InsertChatSettings,
  type ServiceReminder,
  type InsertServiceReminder,
  type ServiceReminderHistory,
  type InsertServiceReminderHistory,
  type MaintenanceSchedule,
  type InsertMaintenanceSchedule,
  type Lead,
  type InsertLead,
  type LeadActivity,
  type InsertLeadActivity,
  type CustomerTag,
  type InsertCustomerTag,
  type CustomerTagAssignment,
  type InsertCustomerTagAssignment,
  type CustomerSegment,
  type InsertCustomerSegment,
  type RentalVehicle,
  type InsertRentalVehicle,
  type RentalExtra,
  type InsertRentalExtra,
  type RentalReservation,
  type InsertRentalReservation,
  type RentalReservationExtra,
  type InsertRentalReservationExtra,
  type RentalContract,
  type InsertRentalContract,
  type RentalPayment,
  type InsertRentalPayment,
  type RentalMaintenance,
  type InsertRentalMaintenance,
  type RentalAvailabilityBlock,
  type InsertRentalAvailabilityBlock,
  type TowTruck,
  type InsertTowTruck,
  type WreckerDriver,
  type InsertWreckerDriver,
  type ThirdPartyWrecker,
  type InsertThirdPartyWrecker,
  type TowPricingZone,
  type InsertTowPricingZone,
  type TowRequest,
  type InsertTowRequest,
  type TowRequestLocation,
  type InsertTowRequestLocation,
  type Expense,
  type InsertExpense,
  type UpdateExpense,
  type Vendor,
  type InsertVendor,
  type VendorBill,
  type InsertVendorBill,
  type VendorBillLineItem,
  type InsertVendorBillLineItem,
  type VendorPayment,
  type InsertVendorPayment,
  type PaymentReminderSettings,
  type InsertPaymentReminderSettings,
  type PaymentReminderLog,
  type InsertPaymentReminderLog,
  type AppointmentSettings,
  type InsertAppointmentSettings,
  type PaymentGatewaySettings,
  type InsertPaymentGatewaySettings,
  type QuickBooksSettings,
  type InsertQuickBooksSettings,
  type Permission,
  type Role,
  type RolePermission,
  type UserPermissionOverride,
  type PermissionAuditLog,
  type NotificationPreferences,
  type NotificationHistory,
  type BadgeCounts,
} from "@shared/schema";

// Re-export commonly used Drizzle ORM functions
export { eq, and, or, desc, asc, sql, gte, lte, like, ilike, inArray, notInArray, isNull, isNotNull, count, sum } from "drizzle-orm";
